## 1.3 Numpy

### 1.3.1 Numpy ndarray 개요

교재 pp. 13-38.

Numpy  

* numerical Python

* 여러 가지 과학, 공학용 파이썬 패키지의 기본이 되는 패키지

* 행렬, 벡터 등 배열 데이터를 다루는 선형대수 연산에 적절한 패키지

* 넘파이와 판다스 : 교재 14쪽 설명 참조

In [1]:
import numpy as np

넘파이의 기본은 다차원배열(ndarray)이며, array() 함수로 만들 수 있다.

array1이라는 이름의 **1차원 배열**을 만든 다음 type()과 shape을 연습하자.

In [2]:
array1 = np.array([1,2,3])
array1

array([1, 2, 3])

In [3]:
print('array1 type:',type(array1))
print('array1 array 형태:',array1.shape)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)


**2차원 배열(행렬)** array2도 만들어보자.

In [4]:
array2 = np.array([[1,2,3],
                  [2,3,4]])
array2

array([[1, 2, 3],
       [2, 3, 4]])

In [5]:
print('array2 type:',type(array2))
print('array2 array 형태:',array2.shape)

array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)


아래와 같이 array3을 만들면 그 원소들은 1차원배열 array1과 같지만 $1 \times 3$ 2차원 배열이 된다.

In [6]:
array3 = np.array([[1,2,3]])
array3

array([[1, 2, 3]])

In [7]:
print('array3 type:',type(array3))
print('array3 array 형태:',array3.shape)

array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


ndarray 배열의 차원은 shape으로 알 수 있고 ndim으로도 확인할 수 있다.

In [8]:
print('array1: {:0}차원, array2: {:1}차원, array3: {:2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1: 1차원, array2: 2차원, array3:  2차원


### 1.3.2 ndarray의 데이터타입(dtype)

int(정수), float(실수), U(유니코드 문자열)

* 정수로만 이루어진 리스트 list1을 가지고 만든 1차원 배열 array1

In [9]:
list1 = [1,2,3]
print(type(list1))

<class 'list'>


In [10]:
array1 = np.array(list1)
print(type(array1))

<class 'numpy.ndarray'>


In [11]:
print(array1, array1.dtype)

[1 2 3] int32


* 정수와 문자열로 이루어진 리스트 list2를 가지고 만든 1차원 배열 array2의 "dtype"

In [12]:
list2 = [1, 2, 'test']
list2

[1, 2, 'test']

In [13]:
array2 = np.array(list2)
print(array2, array2.dtype)

['1' '2' 'test'] <U11


In [14]:
array2

array(['1', '2', 'test'], dtype='<U11')

* 정수와 실수로 이루어진 리스트 list3를 가지고 만든 1차원 배열 array3

In [15]:
list3 = [1, 2, 3.0]
array3 = np.array(list3)
array3

array([1., 2., 3.])

In [16]:
print(array3, array3.dtype)

[1. 2. 3.] float64


* 배열의 dtype 바꾸기**(astype)**

실수를 정수로 변환하면 ```소수점 아래를 반올림하지 않고 버린다```.

In [17]:
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

[1. 2. 3.] float64


In [18]:
array_int1= array_float.astype('int32')
print(array_int1, array_int1.dtype)

[1 2 3] int32


In [19]:
array_float1 = np.array([1.9, 2.1, 3.5])
array_int2= array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1 2 3] int32


아래와 같이 해도 마찬가지. (뒤에 숫자 64, 32 안써도 똑같다!)

In [20]:
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float')
print(array_float, array_float.dtype)

[1. 2. 3.] float64


### 1.3.3 ndarray를 편리하게 생성하기 - arange, zeros, ones

* 연속적인 숫자값 배열 만들기 arange(start, stop, step)

In [21]:
sequence_array = np.arange(10)
print(sequence_array)

[0 1 2 3 4 5 6 7 8 9]


In [22]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
sequence_array = np.arange(101)
print(sequence_array)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100]


In [24]:
print(sequence_array.dtype, sequence_array.shape)

int32 (101,)


In [25]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
np.arange(10, 0, -1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [27]:
np.arange(2, 12, 2)

array([ 2,  4,  6,  8, 10])

- ex) 마지막값은 포함되지 않기 때문에 위의 결과와 같음.

In [28]:
np.arange(2, 11, 2)

array([ 2,  4,  6,  8, 10])

* 모든 값이 0인 배열 만들기

In [29]:
zero_array = np.zeros((3,2),dtype='int32')
print(zero_array)

[[0 0]
 [0 0]
 [0 0]]


In [30]:
zero_array = np.zeros((3,2),dtype='float')
print(zero_array)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [31]:
zero_array = np.zeros((3,2))
print(zero_array)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [32]:
print(zero_array.dtype, zero_array.shape)

float64 (3, 2)


* 모든 값이 1인 배열 만들기

In [33]:
one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


### 1.3.4 배열의 차원과 크기를 바꾸는 reshape

- :\n : 한줄 띄우기

In [34]:
array1 = np.arange(10)
print('array1:\n', array1)

array1:
 [0 1 2 3 4 5 6 7 8 9]


In [35]:
array1 = np.arange(10)
print('array1', array1)

array1 [0 1 2 3 4 5 6 7 8 9]


In [36]:
array2 = array1.reshape(2,5)
print('array2:\n',array2)

array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]


In [37]:
array2.ndim

2

In [38]:
array3 = array1.reshape(5,2)
print('array3:\n',array3)

array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [39]:
array3.ndim

2

- 오류가 생기는 경우 (갯수를 맞춰야함)

In [40]:
array1.reshape(4,3)

ValueError: cannot reshape array of size 10 into shape (4,3)

* 인자가 -1인 reshape (나름 중요)

In [ ]:
array1 = np.arange(10)
print(array1)

In [ ]:
array2 = array1.reshape(-1,5)
print('array2 shape:',array2.shape)

In [ ]:
array2

In [ ]:
array3 = array1.reshape(5,-1)
print('array3 shape:',array3.shape)

In [41]:
array3

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

물론, 아래와 같이 하면 안된다.

In [42]:
array1 = np.arange(10)
array4 = array1.reshape(-1,4)

ValueError: cannot reshape array of size 10 into shape (4)

reshpae()의 인자로 -1을 이용해서 3차원, 또는 1차원 배열을 2차원 배열로 바꾸기

In [43]:
array1 = np.arange(8)
array1

array([0, 1, 2, 3, 4, 5, 6, 7])

In [44]:
array3d = array1.reshape((2,2,2))
array3d

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [45]:
print('array3d:\n',array3d.tolist())

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]


위의 코드에서 3차원 배열을 **tolist()**를 이용하여 `리스트로 바꾼 것`은 단지 출력 결과를 간편하게 보기 위해서다. 리스트로 바꾸기 전 3차원 배열 array3d는 아래와 같다.

In [46]:
# 3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1,1)
print('array5:\n',array5)
print('array5 shape:',array5.shape)

array5:
 [[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]
array5 shape: (8, 1)


In [47]:
# 1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1,1)
print('array6:\n',array6)
print('array6 shape:',array6.shape)

array6:
 [[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]
array6 shape: (8, 1)


### 1.3.5 indexing

교재 23쪽 설명을 보라.

* 인덱싱, 슬라이싱
 * indexing
 * slicing
 * fancy indexing
 * Boolean indexing

* 단일값 추출

In [48]:
# 1에서 부터 9 까지의 1차원 ndarray 생성 
array1 = np.arange(start=1, stop=10)
print('array1:',array1)

array1: [1 2 3 4 5 6 7 8 9]


In [49]:
# index는 0 부터 시작하므로 array1[2]는 3번째 index 위치의 데이터 값을 의미
value = array1[2]
print('value:',value)

value: 3


In [50]:
type(array1)

numpy.ndarray

In [51]:
print(type(value))

<class 'numpy.int32'>


- 기억할 것 :  1차원 배열 array1에서 하나의 데이터만 추출하면 그 결과는 더 이상 ndarray 타입이 아니다.

In [52]:
print('맨 뒤의 값:',array1[-1], ', 맨 뒤에서 두번째 값:',array1[-2])

맨 뒤의 값: 9 , 맨 뒤에서 두번째 값: 8


인덱스를 이용한 배열값 수정

In [53]:
array1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
array1[0] = 9
array1[8] = 0
print('array1:',array1)

array1: [9 2 3 4 5 6 7 8 0]


* 2차원 배열의 indexing

In [55]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [56]:
print('(row=0,col=0) index 가리키는 값:', array2d[0,0] )
print('(row=0,col=1) index 가리키는 값:', array2d[0,1] )
print('(row=1,col=0) index 가리키는 값:', array2d[1,0] )
print('(row=2,col=2) index 가리키는 값:', array2d[2,2] )

(row=0,col=0) index 가리키는 값: 1
(row=0,col=1) index 가리키는 값: 2
(row=1,col=0) index 가리키는 값: 4
(row=2,col=2) index 가리키는 값: 9


#### 참고

교재 25쪽 그림을 잘 보자.

특히 축의 방향을 나타내는 **axis0** (위에서 아래로 행의 번호는 매기는 방향), **axis1** (왼쪽에서 오른쪽으로 열의 번호를 매기는 방향)을 잘 구별하자.

### Slicing

In [57]:
array1 = np.arange(start=1, stop=10)
array1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


교재 27쪽 그림을 보라.

In [59]:
array1 = np.arange(start=1, stop=10)
array4 = array1[:3]
print(array4)

[1 2 3]


In [60]:
array5 = array1[3:]
print(array5)

[4 5 6 7 8 9]


In [61]:
array6 = array1[:]
print(array6)

[1 2 3 4 5 6 7 8 9]


- 퀴즈 : 아래 둘을 비교해보자. 차이가 무엇인가 ?
dtype이 a1은 ndarray이고, a2는 정수(상수)이다.

In [62]:
array1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
a1 = array1[1 : 2]
print(a1)

[2]


In [64]:
a2 = array1[1]
print(a2)

2


In [65]:
print(type(a1), type(a2))

<class 'numpy.ndarray'> <class 'numpy.int32'>


- 퀴즈 : 추출하고 싶은 데이터들이 연속적인 값이 아니라면, 또는 원래 순서와 다르게 추출하고 싶다면 어떻게 할까?

In [66]:
array1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
a3 = array1[1: 4: 2]
a3

array([2, 4])

In [68]:
a4 = array1[::-1]
a4

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

- 퀴즈 : 아래 a5, a6, a7의 출력결과는?

In [69]:
array1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
a5 = array1[-1: 1: -2]
a5

array([9, 7, 5, 3])

In [71]:
a6 = array1[-1::]
a6

array([9])

In [72]:
a7 = array1[:-1:]
a7

array([1, 2, 3, 4, 5, 6, 7, 8])

In [73]:
array1[::]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
array1[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

2차원 배열의 슬라이싱

교재 29쪽 그림을 볼 것.

In [75]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print('array2d:\n',array2d)

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [76]:
print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2])

array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]


In [77]:
print('array2d[1:3, 0:3] \n', array2d[1:3, 0:3])

array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]


In [78]:
print('array2d[1:3, :] \n', array2d[1:3, :])

array2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]


In [79]:
print('array2d[:, :] \n', array2d[:, :])
print('array2d[:2, 1:] \n', array2d[:2, 1:])
print('array2d[:2, 0] \n', array2d[:2, 0])

array2d[:, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:] 
 [[2 3]
 [5 6]]
array2d[:2, 0] 
 [1 4]


2차원 배열 인덱싱이 하나만 있으면? 1차원 배열이 생긴다.

In [80]:
array2d.shape

(3, 3)

In [81]:
array2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [82]:
print(array2d[0])

[1 2 3]


In [83]:
print(array2d[1])

[4 5 6]


In [84]:
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape )

array2d[0] shape: (3,) array2d[1] shape: (3,)


아래와 마찬가지.

In [85]:
print(array2d[0,:])
print(array2d[1,:])

[1 2 3]
[4 5 6]


In [86]:
print(array2d[0,:].shape, array2d[1,:].shape)

(3,) (3,)


### fancy indexing

인덱스 집합을 리스트나 다른 배열로 지정하는 방법(교재 코드와 약간 다름).

In [87]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
array2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

밑에 차이 구별하기!

In [88]:
a3 = array2d[0:2,2]
a3

array([3, 6])

In [89]:
array3 = array2d[[1, 0], 2]
print(array3, type(array3))

[6 3] <class 'numpy.ndarray'>


In [90]:
array4 = array2d[[2,0], 0:2]
print(array4)

[[7 8]
 [1 2]]


In [91]:
array5 = array2d[[0,2]]
print(array5)

[[1 2 3]
 [7 8 9]]


* Boolean indexing

In [92]:
array1d = np.arange(start=1, stop=10)
array1d

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [93]:
# [ ] 안에 array1d > 5 Boolean indexing을 적용 
array3 = array1d[array1d > 5]
print(array3)

[6 7 8 9]


In [94]:
array1d > 5

array([False, False, False, False, False,  True,  True,  True,  True])

밑에는 그냥 설명이다. 밑에 처럼 쓰지 않는다.

In [95]:
boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])
array3 = array1d[boolean_indexes]
print(array3)

[6 7 8 9]


아래와 마찬가지.

In [96]:
indexes = np.array([5,6,7,8])
array4 = array1d[ indexes ]
print(array4)

[6 7 8 9]


### 1.3.6 행렬의 정렬 – sort( )와 argsort( )

* 행렬 정렬

In [97]:
org_array = np.array([ 3, 1, 9, 5]) 
print('원본 행렬:', org_array)

원본 행렬: [3 1 9 5]


**np.sort()** 로 정렬하면 `원본은 그대로 두고 크기에 따라 나열된 새로운 배열이 생긴다.` 하지만 **ndarray.sort( )** 로 정렬하면 `크기에 따라 배열된 새로운 배열이 원본을 대체한다.`

먼저 할당문 없이 np.sort()와 ndarray.sort( )를 실행해서 결과를 비교해보자.

In [98]:
np.sort(org_array) 

array([1, 3, 5, 9])

In [99]:
org_array.sort()
org_array

array([1, 3, 5, 9])

할당문을 추가해서 실행해보면 둘의 차이를 잘 알 수 있다.

In [100]:
# np.sort( )로 정렬 
org_array = np.array([3,1,9,5])
sort_array1 = np.sort(org_array)         
print ('np.sort( ) 호출 후 반환된 정렬 행렬:', sort_array1) 
print('np.sort( ) 호출 후 원본 행렬:', org_array)

np.sort( ) 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort( ) 호출 후 원본 행렬: [3 1 9 5]


In [101]:
# ndarray.sort( )로 정렬
org_array = np.array([3,1,9,5])
sort_array2 = org_array.sort()
print('org_array.sort( ) 호출 후 반환된 행렬:', sort_array2)
print('org_array.sort( ) 호출 후 원본 행렬:', org_array)

org_array.sort( ) 호출 후 반환된 행렬: None
org_array.sort( ) 호출 후 원본 행렬: [1 3 5 9]


`내림차순`으로 정렬하려면, 

In [102]:
sort_array1_desc = np.sort(org_array)[::-1]
print ('내림차순으로 정렬:', sort_array1_desc) 

내림차순으로 정렬: [9 5 3 1]


2차원 배열에 대해 행을 기준으로, 또는 열을 기준으로 정렬하려면,

In [103]:
array2d = np.array([[8, 12], [7, 1]])
array2d

array([[ 8, 12],
       [ 7,  1]])

`axis=0` 으로 지정하면 `행번호`를 따라 이동하면서 정렬하므로 각 열 내부에서 크기 순으로 정렬된다.

In [104]:
sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]


`axis=1` 으로 지정하면 `열번호`를 따라 이동하면서 정렬하므로 각 행 내부에서 크기 순으로 정렬된다.

In [105]:
sort_array2d_axis1 = np.sort(array2d, axis=1)
print('컬럼 방향으로 정렬:\n', sort_array2d_axis1)

컬럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


* 정렬 행렬의 인덱스 반환 **np.argsort()**

In [106]:
org_array = np.array([ 3, 1, 9, 5]) 
sort_indices = np.argsort(org_array)
print(sort_indices)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

[1 0 3 2]
<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [107]:
org_array = np.array([ 3, 1, 9, 5]) 
sort_indices_desc = np.argsort(org_array)[::-1]
print(sort_indices_desc)
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

[2 3 0 1]
행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


argsort() 활용 예 : 점수 순서에 따라 학생들의 이름을 출력하고 싶다면,

In [108]:
name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array= np.array([78, 95, 84, 98, 88])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


### 1.3.7 선형대수 연산 – 행렬 곱셈과 전치 행렬 구하기

* 행렬 곱셈 np.dot()

In [109]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

np.dot(A, B)

array([[ 58,  64],
       [139, 154]])

In [110]:
type(A)

numpy.ndarray

In [111]:
A.shape

(2, 3)

In [112]:
np.dot(B, A)

array([[ 39,  54,  69],
       [ 49,  68,  87],
       [ 59,  82, 105]])

In [113]:
A.dot(B)

array([[ 58,  64],
       [139, 154]])

* 전치 행렬 transpose()

In [114]:
np.transpose(A)

array([[1, 4],
       [2, 5],
       [3, 6]])

위와 동일

In [115]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [116]:
A = np.array([[1, 2],
              [3, 4]])
np.transpose(A)

array([[1, 3],
       [2, 4]])

- 참고 : numpy의 matrix() 함수로도 행렬을 만들 수 잇는데 이렇게 만든 행렬을 곱하는 연산자는 * 이다.

In [117]:
a2 = np.arange(12).reshape(3,4)
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [118]:
type(a2)

numpy.ndarray

In [119]:
C = np.matrix(a2)
C

matrix([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [120]:
type(C)

numpy.matrix

In [121]:
C * np.transpose(C)

matrix([[ 14,  38,  62],
        [ 38, 126, 214],
        [ 62, 214, 366]])

In [122]:
np.transpose(C) * C

matrix([[ 80,  92, 104, 116],
        [ 92, 107, 122, 137],
        [104, 122, 140, 158],
        [116, 137, 158, 179]])

수업시간 질문

In [123]:
b1 = np.arange(10,100,10).reshape(3,3)
b1

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [124]:
b2 = b1[1:3]
b2

array([[40, 50, 60],
       [70, 80, 90]])

In [125]:
b3 = b2[1]
b3

array([70, 80, 90])

In [126]:
b4 = b2[1:2]
b4

array([[70, 80, 90]])

In [127]:
b5 = b2[1:3]
b5

array([[70, 80, 90]])

In [128]:
b1[1:3][1:3]

array([[70, 80, 90]])

In [129]:
b1[1:3, 1:3]

array([[50, 60],
       [80, 90]])