### 2.3 사이킷런의 기반 프레임워크 익히기

#### 2.3.1 Estimator, fit(), predict()

* class : 객체를 만드는 틀(붕어빵, 앙금빵, 팥빵 등의 인스턴스 객체를 만드는 빵틀)
 * Classifier : `분류` 알고리즘을 구현하는 클래스 
 * Regressor : `회귀`분석 알고리즘을 구현하는 클래스
 * Estimator : 분류, 회귀 등의 지도학습 알고리즘을 구현하는 클래스의 통칭 (fit(), predict() 메서드가 필수적).
 
세부적인 분류, 회귀 클래스들에 대해서는 교재 94쪽 그림을 볼 것.

#### 2.3.2 사이킷런의 주요 모듈, 2.4.2 내장된 예제 데이터세트

* 주요 모듈 : 교재 94-95쪽 참조.

* 예제 데이터 : 교재 96쪽.

In [1]:
from sklearn.datasets import load_iris

iris_data = load_iris()
print(type(iris_data))

<class 'sklearn.utils.Bunch'>


97쪽의 데이터 설명을 잘 읽어보자.

In [2]:
keys = iris_data.keys()
print('붓꽃 데이터 세트의 키들:', keys)

붓꽃 데이터 세트의 키들: dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])


위의 코드로 딕셔너리 형식으로 된 불꽃 데이터 세트에 있는 키들을 확인한다. `data, target, feature_names, target_names` 키를 설명하는 98쪽의 그림을 잘 보자. 키 카운대 DESCR은 데이터에 대한 설명서다.

In [3]:
print('\n feature_names 의 type:',type(iris_data.feature_names))
print(' feature_names 의 shape:',len(iris_data.feature_names))
print(iris_data.feature_names)


 feature_names 의 type: <class 'list'>
 feature_names 의 shape: 4
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [4]:
print('\n target_names 의 type:',type(iris_data.target_names))
print(' feature_names 의 shape:',len(iris_data.target_names))
print(iris_data.target_names)


 target_names 의 type: <class 'numpy.ndarray'>
 feature_names 의 shape: 3
['setosa' 'versicolor' 'virginica']


In [5]:
print('\n data 의 type:',type(iris_data.data))
print(' data 의 shape:',iris_data.data.shape)
print(iris_data['data'][:5])


 data 의 type: <class 'numpy.ndarray'>
 data 의 shape: (150, 4)
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [6]:
print('\n target 의 type:',type(iris_data.target))
print(' target 의 shape:',iris_data.target.shape)
print(iris_data.target)


 target 의 type: <class 'numpy.ndarray'>
 target 의 shape: (150,)
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
